version: '3.5'
services:
  recorder:
    #restart: unless-stopped
    build:
      context: .
    volumes:
      - /var/test:/tmp/records
    #user: "1000"
    environment:
      - RECORD_CAM1-SNAPSHOT_TYPE=snapshot
      - RECORD_CAM1-SNAPSHOT_URL=http://user:pass@192.168.1.50/api/v1/snap.cgi?chn=1
      - RECORD_CAM1-SNAPSHOT_SCHEDULE=5s
      - RECORD_CAM1-SNAPSHOT_KEEP_TIME=10m
      - RECORD_CAM1-SNAPSHOT_PRUNE_SCHEDULE=30m
      - RECORD_CAM1-SNAPSHOT_FILE_FORMAT=/tmp/records/cam1/{date}/{datetime}.jpg

      - RECORD_CAM2-SNAPSHOT_TYPE=snapshot
      - RECORD_CAM2-SNAPSHOT_URL=http://user:pass@192.168.1.50/api/v1/snap.cgi?chn=0
      - RECORD_CAM2-SNAPSHOT_SCHEDULE=10s
      - RECORD_CAM2-SNAPSHOT_KEEP_TIME=1h
      - RECORD_CAM2-SNAPSHOT_PRUNE_SCHEDULE=1h
      - RECORD_CAM2-SNAPSHOT_FILE_FORMAT=/tmp/records/cam2/{date}/{datetime}.jpg

      #- LOG_LEVEL=debug
